---
loglevel: debug
logfile: tmp/registry.log

http:
  base_url: localhost
  port: 6799
  user: admin
  password: admin

db:
  adapter: mysql2
  user: registry     
  password: registry 
  host: 127.0.0.1    
  port: 3306        
  database: registry
  connection_options: 
      max_connections: 32
      pool_timeout: 10

cloud:
  login_url: <dashboard login url>  # appear in email only
  plugin: openstack 
  default_role:  # add user to new tenant in this role
  openstack:
    auth_url: <%= auth_url %>
    username: <%= username %>
    api_key: <%= api_key %>  # your openstack password
    tenant: <%= tenant %>

mail:
  admin_emails:
  worker: 
  smtp_server: 
  port: 
  helo: 
  username: 
  password: 
  authentication: 
